#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Specify a number of replicas"
    exit
fi

#using aws key vals (note: this file is not committed to vc):
#source aws_keyvals.txt

#pulling image from aws ecr
#docker pull ${AWS_ACCOUNT}.${ECR_RESOURCE_URI}:latest

#run from manager
docker service create --replicas $1 --name poolgp poolgp_server:latest
